name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Beijing build date
        run: echo "BUILD_DATE=$(TZ=Asia/Shanghai date +'%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: Build and push for ${{ matrix.platform }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: ${{ matrix.platform }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/conflux:${{ env.BUILD_DATE }}-${{ matrix.platform##*/ }}
          build-args: |
            BUILD_DATE=${{ env.BUILD_DATE }}
          cache-from: type=gha,scope=${{ matrix.platform }}
          cache-to: type=gha,mode=max,scope=${{ matrix.platform }}
          provenance: false
          sbom: false

  merge-manifest:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create unified multi-arch tag
        run: |
          docker buildx imagetools create \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/conflux:${{ env.BUILD_DATE }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/conflux:latest \
            ${{ secrets.DOCKERHUB_USERNAME }}/conflux:${{ env.BUILD_DATE }}-amd64 \
            ${{ secrets.DOCKERHUB_USERNAME }}/conflux:${{ env.BUILD_DATE }}-arm64
